#!/bin/sh
for i in $(seq 1 $1)
do
	echo "Running instance $i"
	start=`date +%s%N`
	../Build/dp search in/input$i.txt leveledSetSearch > out.txt
	tt=$((($(date +%s%N) - $start)/1000000))
	echo "$tt milliseconds"
	if (! cmp out.txt out/output$i.txt) then
		echo "WRONG OUTPUT\n"
		#break
	else
		echo "OK\n"
	fi
done
rm out.txt
