#!/bin/sh
make -C ../Build
echo ""
for i in $(seq 1 $1)
do
	echo "Running instance $i"
	start=`date +%s%N`
	mem=$( (time -f "%M" ../Build/dp search in/input$i.txt leveledSetSearch > out.txt) 2>&1)
	tt=$((($(date +%s%N) - $start)/1000000))

	echo "$(($mem/1024)) MB"
	echo "$tt milliseconds"
	if (! cmp out.txt out/output$i.txt) then
		echo "WRONG OUTPUT\n"
		#break
	else
		echo "OK\n"
	fi
done
rm out.txt
